export enum ProofType {
  JUBMOJI_IN_COLLECTION = "JUBMOJI_IN_COLLECTION",
  JUBMOJI_IN_COLLECTION_NONCE = "JUBMOJI_IN_COLLECTION_NONCE",
  N_UNIQUE_JUBMOJI_IN_COLLECTION = "N_UNIQUE_JUBMOJI_IN_COLLECTION",
  PUBLIC_MESSAGE_SIGNATURE = "PUBLIC_MESSAGE_SIGNATURE",
}
